### PR TITLE
generate META.json

### PR DESCRIPTION
**Pull request by Grinnz**
META.json is the modern format for CPAN metadata, all distributions should generate it. Also changed the dzil copy logic to copy META.json instead of META.yml.

FWIW my [Starter](https://metacpan.org/pod/Dist::Zilla::PluginBundle::Starter) bundle includes a modern pluginset like this, allows direct use of MakeMaker::Awesome, and implements a `regenerate` option which is somewhat nicer than copy-on-build. I could make a PR to convert to that bundle if you were interested.

### CODE REVIEW

**Comment by nwellnhof** [comment]
> all distributions should generate it

Why? AFAIK, older Perl versions only work with `META.yml` out-of-the-box, so we'd have to ship with both JSON and YAML files. Unless there's a tangible benefit of providing `META.json`, I see no reason to add it.

**Comment by Grinnz** [comment]
[CPAN::Meta::Spec 2](https://metacpan.org/pod/CPAN::Meta::Spec), which has been the current version of the spec for a decade now, is only supported by META.json. It supports many features the old version does not, such as multiple licenses, static dist prereqs (indicated by dynamic_config 0), recommended/suggested prereq types in all phases, separate web urls for repository metadata, and custom keys such as the experimental static install and contributors metadata. The more distributions that continue to supply only META.yml, especially driven by dist.ini where it is so trivial to generate META.json, the longer we are prevented from moving the ecosystem forward.

**Comment by nwellnhof** [comment]
> separate web urls for repository metadata

OK, that's really useful.

> recommended/suggested prereq types in all phases

This also might be useful at some point.

> The more distributions that continue to supply only META.yml, especially driven by dist.ini where it is so trivial to generate META.json, the longer we are prevented from moving the ecosystem forward.

META.yml must and will be supported for quite some time and I don't see how its existence holds back the ecosystem. The change is trivial though, so I'll add META.json in addition to META.yml.

**Comment by Grinnz** [comment]
I was referring to the lack of META.json rather than the existence of META.yml, as you noted the latter must continue to be included to support old CPAN installers for some time.

**Pull request closed without merging**
